wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
    - ./data/html:/var/www/html
    - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

db:
  image: mariadb
  volumes:
    - ./data/mysql:/var/lib/mysql
  env_file:
    - ./env

