wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - ./data/html:/var/www/html

db:
  image: mariadb
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: example


