wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
    - ./data/html:/var/www/html

db:
  image: mariadb
  volumes:
    - ./data/mysql:/var/lib/mysql
  env_file:
    - ./env

